apiVersion: apps/v1
kind: Deployment
metadata:
  name: legal-management-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: legal-management-system
  template:
    metadata:
      labels:
        app: legal-management-system
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: [ 'sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 2; done' ]
      containers:
        - name: legal-management-system
          image: legal-management-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: legal-management-system
spec:
  selector:
    app: legal-management-system
  ports:
    - port: 80
      targetPort: 8080